version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u0z2s2z8
      - echo Logging in to Docker Hub
      - docker login --username skoranda --password $HUB_DOCKER_COM_TOKEN
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - git checkout develop
      - container/build.sh basic_auth --tag_suffix 1
      - LAST_TAG=$(docker images --format "{{.Tag}}" | head -n 1)
      - docker tag comanage-registry:$LAST_TAG  public.ecr.aws/u0z2s2z8/comanage-registry:$LAST_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/u0z2s2z8/comanage-registry:$LAST_TAG
